### ISSUE TITLE
Error with pod install

### ISSUE THREAD

**Issue by francesc-o** [HamzaGhazouani/HGRippleRadarView#1]
Hi,
I have a problem with the installation through CocoaPods. When I run the command pod install, I receive this error: `[!] Unable to find a specification for 'HGRippleRadarView'`. 
Do you have any suggestion about that? Thanks

**Comment by HamzaGhazouani** [comment]
Hi @francesc-o, 
I think your local specs are not up to date, just run `pod update` and it will work fine :) 
Hamza

**Comment by francesc-o** [comment]
Yeah it works, thank you very much (the library is very good).

**Comment by francesc-o** [comment]
Yeah it works, thank you very much (the library is very good).

**Comment by HamzaGhazouani** [comment]
Thanks @francesc-o, awesome to hear 😀
